import React, { useContext } from 'react';
import clsx from 'clsx';
import {
  useCurrentSidebarCategory,
  filterDocCardListItems,
} from '@docusaurus/plugin-content-docs/client';
import DocCard from '@theme/DocCard';

/* dbt Customizations:
 * Import version context and utils
 * Get versionedPages/versionedCategories from website/dbt-versions.js
 * Get version + product from context
 * Hide cards on autogenerated index pages when they are not available
 * for the current version/product (mirrors DocSidebarItem behavior)
*/
import {usePluginData} from '@docusaurus/useGlobalData';
import VersionContext from '../../stores/VersionContext';
import pageVersionCheck from '../../utils/page-version-check';
import categoryVersionCheck from '../../utils/category-version-check';

function useVersionedCardItems(items) {
  const { versionedPages, versionedCategories } = usePluginData(
    'docusaurus-build-global-data-plugin'
  );
  const { version, product } = useContext(VersionContext);

  return filterDocCardListItems(items).filter((item) => {
    // Hide versionedPages that do not match the current version or product
    if (versionedPages) {
      const { pageAvailable } = pageVersionCheck(
        version,
        versionedPages,
        item.docId,
        product
      );
      if (!pageAvailable) return false;
    }

    // Hide versionedCategories that do not match the current version or product
    if (versionedCategories && item.type === 'category') {
      const { categoryAvailable } = categoryVersionCheck(
        version,
        versionedCategories,
        item.label,
        product
      );
      if (!categoryAvailable) return false;
    }

    return true;
  });
}

function DocCardListForCurrentSidebarCategory({className}) {
  const category = useCurrentSidebarCategory();
  return <DocCardList items={category.items} className={className} />;
}
export default function DocCardList(props) {
  const {items, className} = props;
  if (!items) {
    return <DocCardListForCurrentSidebarCategory {...props} />;
  }
  // dbt custom: filter items by current version/product
  const filteredItems = useVersionedCardItems(items);
  return (
    <section className={clsx('row', className)}>
      {filteredItems.map((item, index) => (
        <article key={index} className="col col--6 margin-bottom--lg">
          <DocCard item={item} />
        </article>
      ))}
    </section>
  );
}
