name: Improve content
description: Make a suggestion to improve the content in an existing page.
labels: ["content","improvement"]
body:
  - type: markdown
    attributes:
      value: |
        * You can ask questions or submit ideas for the dbt docs in [Issues](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose)
        * Before you file an issue read the [Contributing guide](https://github.com/dbt-labs/docs.getdbt.com#contributing).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/dbt-labs/docs.getdbt.com/issues).

  - type: checkboxes
    id: contributions
    attributes:
      label: Contributions
      description: Please read the contribution docs before opening an issue or pull request.
      options:
        - label: I have read the contribution docs, and understand what's expected of me. 

  - type: textarea
    attributes:
      label: Link to the page on docs.getdbt.com requiring updates
      description: Please link to the page or pages you'd like to see improved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the page would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
