blank_issues_enabled: true
contact_links:
  - name: Have questions about dbt? Join the Community!
    url: https://www.getdbt.com/community/join-the-community
    about: You can join the dbt Labs Community to ask and answer questions.
