name: Start docs project for a new feature
description: For dbt PMs to add docs for their new or updated dbt product features.
labels: ["content","upcoming release"]
body:
  - type: markdown
    attributes:
      value: |
        * Before you file an issue read the [Contributing guide](https://github.com/dbt-labs/docs.getdbt.com#contributing).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/dbt-labs/docs.getdbt.com/issues).

  - type: checkboxes
    id: contributions
    attributes:
      label: Contributions
      description: This applies to new, unreleased content.
      options:
        - label: I am a PM or subject matter expert at dbt who is responsible for this feature. 

  - type: textarea
    attributes:
      label: Where does this content belong?
      description: |
        - Give as much detail as you can to help us understand where you expect the content to live.  
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link to source material
      description: |
        Use the [source material template](https://docs.google.com/document/d/1lLWGMXJFjkY4p7r8ZKhBX73dOLmIjgXZBYq39LqmAJs/edit) to provide source material for this feature. 
    validations:
      required: true