name: Promote Discussion to Blog Content
description: >
  For promoting a Discussion that's been approved for outlining to an Issue so it can be crafted into
  new content on the Developer Blog section of the Developer Hub.
labels: ["content","developer blog"]
body:
  - type: markdown
    attributes:
      value: |
        Let's write an article together!
        
        The foundational requirement of this Issue will be an initial outline. This should arrange the content you've laid out in the original Discussion into a structural flow that looks something like this [initial outline example forthcoming].
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: your preferred email and/or dbt Slack handle
    validations:
      required: true


  - type: checkboxes
    id: from-discussion
    attributes:
      label: This issue is being created to promote an approved Discussion.
      description: >
        Creating new content for the Developer Blog should start as a Discussion. Please confirm that you've followed the Discussion path and 
        the Discussion being promoted has been approved with the label 'promote to developer blog issue'.
      options:
        - label: I am promoting this issue from an approved Discussion and will link it below.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link to the Discussion this Issue is promoting.
      description: Please link to the Discussion this Issue is originating from.
    validations:
      required: true

  - type: textarea
    attributes:
      label: >
        If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise,
        please answer these questions below
      description: |
        1. What is the main problem you are solving? What is your solution? _This should help form your core thesis._
        2. Why should the reader care about this problem? Why is your solution the right one? _This should help form your specific target audience._
        3. Can you list the steps of your solution for the reader here? _This should help you form the overall narrative arc and sketch out an example use case to illustrate it._

        Optional

        4. Are there any resources that helped inspire or inform your idea? (eg slack discussions, articles, external product docs, etc. -- if so please link)
        5. Are there other existing solutions that solve the problem, and if so, how is this solution better or different? If so please share any links here.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        In addition to the initial questions from the Discussion, which should form the body and arc of your article, the following questions will help you round out your initial outline with additional context.
        
        1. Is there anything the reader needs to know before they start? 
        2. Are there any tool & skill prerequisites the reader should be aware of?
        3. Are there any drawbacks or tradeoffs to your solution that the reader should know about? Given tradeoffs, can you explain in greater detail the circumstances in which your solution is best deployed?
        4. Are there any additional resources you can point the reader to to give them greater context or preparation on the problem and/or solution?
        5. Can you describe what a (or a few) successful outcomes of your solution could look like?
        
        Use the answers to these questions to strengthen an example use case that will support the arc of your narrative. Lay this out in the introduction of your outline, use it to illustrate your headings throughout, and circle back to it in a conclusion.
        
        Include these introduction and conclusion sections to wrap the steps from your Discussion in your initial outline.
      
  - type: textarea
    attributes:
      label: Link to the initial outline we will develop through this Issue.
      description: Please link to the inital outline in FigJam, Notion, or Google Docs
    validations:
      required: true
