export const FIELD_LABELS = {
  availability: 'Availability',
  availableTo: 'Available to',
  engine: 'Engine',
  engines: 'Engines',
  excludes: 'Does not apply to',
  feature: 'Feature',
  license: 'License',
  notes: 'Notes',
  optional: 'Optional',
  partialSupport: 'Partial support',
  plans: 'Plans',
  product: 'Product',
  registration: 'Registration',
  status: 'Status',
  surface: 'Surface',
  workflow: 'Workflow',
};

export const VALUE_LABELS = {
  availability: {
    open_source: 'Open source',
  },
  availableTo: {
    platform_users: 'dbt platform users',
  },
  engine: {
    core_python: 'dbt Core Python engine',
    fusion: 'dbt Fusion engine',
    core_and_fusion: 'dbt Core Python engine and dbt Fusion engine',
    all_engines: 'All engines',
    not_engine_specific: 'Not engine-specific',
  },
  license: {
    developer: 'Developer license',
    developer_insights: 'Developer license with Insights access',
    free_registration: 'Free dbt platform registration',
    platform_account: 'dbt platform account',
  },
  plans: {
    all_platform_plans: 'All dbt platform plans',
    starter_and_above: 'Starter, Enterprise, and Enterprise+',
    enterprise_and_above: 'Enterprise and Enterprise+',
    enterprise_plus: 'Enterprise+ only',
    none: 'Open source / no dbt platform plan required',
  },
  product: {
    platform: 'dbt platform',
    core: 'dbt Core',
    core_v2: 'dbt Core v2',
    dbt_state: 'dbt State',
    fusion_cli: 'Fusion CLI',
    dbt_cli: 'dbt CLI',
    vscode_extension: 'dbt VS Code extension',
    insights: 'dbt Insights',
    wizard: 'dbt Wizard',
    wizard_cli: 'dbt Wizard CLI',
  },
  status: {
    ga: 'Generally available',
    preview: 'Public preview',
    beta: 'Beta',
    alpha: 'Alpha',
    experimental: 'Experimental',
  },
  surface: {
    platform: 'dbt platform',
    local: 'Local development',
    cli: 'CLI',
    vscode: 'VS Code',
    multiple: 'Multiple surfaces',
  },
  workflow: {
    platform: 'dbt platform',
    local: 'Local development',
    cli: 'CLI',
    vscode: 'VS Code',
    multiple: 'Multiple surfaces',
  },
};

export const availabilityPresets = {
  platform_all_plans: {
    description: 'Use for dbt platform pages available to every platform plan.',
    badge: ['dbt platform', 'All plans'],
    product: 'platform',
    surface: 'platform',
    plans: 'all_platform_plans',
  },
  platform_starter_and_above: {
    description: 'Use for dbt platform pages available to Starter, Enterprise, and Enterprise+.',
    badge: ['dbt platform', 'Starter and above'],
    product: 'platform',
    surface: 'platform',
    plans: 'starter_and_above',
  },
  platform_enterprise: {
    description: 'Use for dbt platform pages available to Enterprise and Enterprise+.',
    badge: ['dbt platform', 'Enterprise'],
    product: 'platform',
    surface: 'platform',
    plans: 'enterprise_and_above',
  },
  platform_enterprise_plus: {
    description: 'Use for dbt platform pages available only to Enterprise+.',
    badge: ['dbt platform', 'Enterprise+'],
    product: 'platform',
    surface: 'platform',
    plans: 'enterprise_plus',
  },
  vscode_fusion_preview: {
    description: 'Use for dbt VS Code extension pages backed by the dbt Fusion engine.',
    badge: ['VS Code extension', 'Fusion'],
    product: 'vscode_extension',
    workflow: 'local',
    surface: 'vscode',
    engine: 'fusion',
    status: 'preview',
    excludes: ['dbt Core with the Python engine'],
  },
  dbt_core_oss: {
    description: 'Use for OSS dbt Core CLI pages.',
    badge: ['CLI', 'dbt Core'],
    product: 'core',
    workflow: 'local',
    surface: 'cli',
    engine: 'core_python',
    availability: 'open_source',
    excludes: ['dbt Fusion engine', 'dbt platform-only workflows'],
  },
  dbt_core_v2_alpha: {
    description: 'Use for dbt Core v2 alpha CLI pages.',
    badge: ['dbt Core v2', 'Fusion', 'Alpha'],
    product: 'core_v2',
    workflow: 'local',
    surface: 'cli',
    engine: 'fusion',
    availability: 'open_source',
    status: 'alpha',
    excludes: ['dbt Core v1 / Python engine behavior'],
  },
  fusion_cli: {
    description: 'Use for Fusion CLI pages.',
    badge: ['Fusion CLI', 'Fusion'],
    product: 'fusion_cli',
    workflow: 'local',
    surface: 'cli',
    engine: 'fusion',
    excludes: ['dbt Core Python engine'],
  },
  cli_all_engines: {
    description: 'Use for CLI pages that apply to every dbt engine.',
    badge: ['CLI', 'All engines'],
    workflow: 'local',
    surface: 'cli',
    engine: 'all_engines',
  },
  dbt_cli_platform_core_fusion: {
    description: 'Use for dbt CLI pages available to dbt platform users across Core and Fusion.',
    badge: ['CLI', 'dbt platform', 'Core and Fusion'],
    product: 'dbt_cli',
    workflow: 'local',
    surface: 'cli',
    availableTo: 'platform_users',
    engine: 'core_and_fusion',
  },
  wizard: {
    description: 'Use for dbt Wizard pages.',
    badge: ['dbt Wizard'],
    product: 'wizard',
    surface: 'platform',
    plans: 'starter_and_above',
  },
  wizard_cli: {
    description: 'Use for dbt Wizard CLI pages.',
    badge: ['dbt Wizard CLI', 'Local development'],
    product: 'wizard_cli',
    workflow: 'local',
    surface: 'cli',
    status: 'beta',
  },
  wizard_platform: {
    description: 'Use for dbt Wizard pages in the dbt platform.',
    badge: ['dbt platform', 'dbt Wizard', 'Starter and above'],
    product: 'wizard',
    surface: 'platform',
    plans: 'starter_and_above',
    status: 'preview',
  },
  dbt_state: {
    description: 'Use for dbt State pages that apply across platform, Core, and Fusion workflows.',
    badge: ['dbt State', 'Core and Fusion', 'Preview'],
    product: 'dbt_state',
    surface: 'multiple',
    engine: 'core_and_fusion',
    status: 'preview',
  },
};
