project_id: '856190'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # Temp for testing
  - source: /docs/docs/introduction.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/docs/introduction.md
  - source: /docs/docs/fusion/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/docs/fusion/%original_file_name%
    
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # # Docs Markdown files
  # - source: /docs/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # # Blog Markdown files
  # - source: /blog/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
