const sidebarSettings = {
  docs: [
    {
      type: 'html',
      value: 'About',
      className: 'sidebar-title',
    },
    "docs/introduction",
    "docs/dbt/get-started-dbt",
    "docs/dbt/dbt-availability",
    "docs/dbt/supported-features",
    "docs/dbt/dbt-releases",
    {
      type: "category",
      label: "About the dbt platform",
      link: { type: "doc", id: "docs/platform/about-platform/dbt-platform-features" },
      items: [
        "docs/platform/about-platform/architecture",
        "docs/platform/about-platform/browsers",
        "docs/platform/about-platform/login",
        "docs/platform/about-platform/change-your-dbt-theme",
        "docs/platform/about-platform/dbt-platform-features",
        "docs/platform/about-platform/access-regions-ip-addresses",
        "docs/platform/about-platform/tenancy",
      ],
    }, // About dbt platform directory
    {
      type: "category",
      label: "Supported data platforms",
      collapsed: true,
      link: { type: "doc", id: "docs/supported-data-platforms" },
      items: [
        "docs/supported-data-platforms",
        "docs/connect-adapters",
        "docs/trusted-adapters",
        "docs/community-adapters",
        "docs/contribute-dbt-adapters",
      ],
    }, // Supported data platforms directory
    {
      type: 'html',
      value: 'Get started',
      className: 'sidebar-title',
    },
    "docs/get-started-dbt",
    {
      type: "category",
      label: "Get started with dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/about-setup" },
      items: [
        "docs/about-setup",
        "docs/environments-in-dbt",
        {
          type: "category",
          label: "dbt platform setup",
          collapsed: true,
          link: { type: "doc", id: "docs/platform/about-platform-setup" },
          items: [
            "docs/platform/about-platform-setup",
            "docs/configuration-checklist",
            "docs/platform/about-profiles",
            "docs/platform/account-settings",
            "docs/platform/account-integrations",
            "docs/dbt-platform-environments",
            "docs/platform/migration",
            {
              type: "category",
              label: "Connect your data platforms",
              link: {
                type: "doc",
                id: "docs/platform/connect-data-platform/about-connections",
              },
              items: [
                "docs/platform/connect-data-platform/about-connections",
                "docs/platform/connect-data-platform/connect-apache-spark",
                "docs/platform/connect-data-platform/connect-amazon-athena",
                "docs/platform/connect-data-platform/connect-azure-synapse-analytics",
                "docs/platform/connect-data-platform/connect-bigquery",
                "docs/platform/connect-data-platform/connect-databricks",
                "docs/platform/connect-data-platform/connect-microsoft-fabric",
                "docs/platform/connect-data-platform/connect-onehouse",
                "docs/platform/connect-data-platform/connect-postgresql-alloydb",
                "docs/platform/connect-data-platform/connect-redshift",
                "docs/platform/connect-data-platform/connect-snowflake",
                "docs/platform/connect-data-platform/connect-starburst-trino",
                "docs/platform/connect-data-platform/connect-teradata",
              ],
            },
            {
              type: "category",
              label: "Manage access",
              link: {
                type: "doc",
                id: "docs/platform/manage-access/about-user-access",
              },
              items: [
                "docs/platform/manage-access/about-user-access",
                "docs/platform/manage-access/invite-users",
                "docs/platform/manage-access/mfa",
                {
                  type: "category",
                  label: "User permissions and licenses",
                  link: {
                    type: "doc",
                    id: "docs/platform/manage-access/seats-and-users",
                  },
                  items: [
                    "docs/platform/manage-access/seats-and-users",
                    "docs/platform/manage-access/enterprise-permissions",
                    "docs/platform/manage-access/self-service-permissions",
                  ],
                },
                {
                  type: "category",
                  label: "Environment permissions",
                  link: {
                    type: "doc",
                    id: "docs/platform/manage-access/environment-permissions",
                  },
                  items: [
                    "docs/platform/manage-access/environment-permissions",
                    "docs/platform/manage-access/environment-permissions-setup",
                  ],
                },
                {
                  type: "category",
                  label: "Single sign-on and OAuth",
                  link: {
                    type: "doc",
                    id: "docs/platform/manage-access/sso-oauth-intro",
                  },
                  items: [
                    {
                      type: "category",
                      label: "SSO",
                      link: {
                        type: "doc",
                        id: "docs/platform/manage-access/sso-overview",
                      },
                      items: [
                        "docs/platform/manage-access/sso-overview",
                        "docs/platform/manage-access/auth0-migration",
                        "docs/platform/manage-access/set-up-sso-saml-2.0",
                        "docs/platform/manage-access/set-up-sso-okta",
                        "docs/platform/manage-access/set-up-sso-google-workspace",
                        "docs/platform/manage-access/set-up-sso-microsoft-entra-id",
                        "docs/platform/manage-access/sso-faq",
                      ],
                    },
                    {
                      type: "category",
                      label: "SCIM",
                      link: {
                        type: "doc",
                        id: "docs/platform/manage-access/scim",
                      },
                      items: [
                        "docs/platform/manage-access/scim",
                        "docs/platform/manage-access/scim-entra-id",
                        "docs/platform/manage-access/scim-okta",
                        "docs/platform/manage-access/scim-manage-user-licenses",
                        "docs/platform/manage-access/scim-faq",
                      ],
                    },
                    {
                      type: "category",
                      label: "OAuth",
                      link: {
                        type: "doc",
                        id: "docs/platform/manage-access/oauth-intro",
                      },
                      items: [
                        "docs/platform/manage-access/oauth-intro",
                        "docs/platform/manage-access/connect-apps-oauth",
                        "docs/platform/manage-access/set-up-snowflake-oauth",
                        "docs/platform/manage-access/set-up-databricks-oauth",
                        "docs/platform/manage-access/set-up-bigquery-oauth",
                        "docs/platform/manage-access/snowflake-external-oauth",
                        "docs/platform/manage-access/redshift-external-oauth",
                      ],
                    },
                  ],
                }, // Single sign-on and OAuth
                "docs/platform/manage-access/audit-log",
              ],
            }, // Manage access

            {
              type: "category",
              label: "Configure Git",
              link: {
                type: "doc",
                id: "docs/platform/git/configure-git",
              },
              items: [
                "docs/platform/git/configure-git",
                "docs/platform/git/managed-repository",
                "docs/platform/git/import-a-project-by-git-url",
                "docs/platform/git/connect-github",
                "docs/platform/git/connect-gitlab",
                {
                  type: "category",
                  label: "Azure DevOps",
                  link: {
                    type: "doc",
                    id: "docs/platform/git/connect-azure-devops",
                  },
                  items: [
                    "docs/platform/git/connect-azure-devops",
                    "docs/platform/git/setup-service-principal",
                    "docs/platform/git/setup-service-user",
                    "docs/platform/git/authenticate-azure",
                  ],
                },
                {
                  type: "category",
                  label: "Git version control",
                  link: {
                    type: "doc",
                    id: "docs/platform/git/git-version-control",
                  },
                  items: [
                    "docs/platform/git/git-version-control",
                    "docs/platform/git/version-control-basics",
                    "docs/platform/git/pr-template",
                    "docs/platform/git/merge-conflicts",
                  ],
                },
              ],
            }, // Supported Git providers
            {
              type: "category",
              label: "Network security",
              link: { type: "doc", id: "docs/platform/secure/about-network-security" },
              items: [
                "docs/platform/secure/about-network-security",
                "docs/platform/secure/ip-restrictions",
                {
                  type: "category",
                  label: "Private connectivity",
                  link: { type: "doc", id: "docs/platform/secure/private-connectivity/private-connectivity" },
                  items: [
                    "docs/platform/secure/private-connectivity/private-connectivity",
                    {
                      type: "category",
                      label: "AWS",
                      link: { type: "doc", id: "docs/platform/secure/private-connectivity/aws/aws-overview" },
                      items: [
                        "docs/platform/secure/private-connectivity/aws/aws-overview",
                        "docs/platform/secure/private-connectivity/aws/aws-snowflake",
                        "docs/platform/secure/private-connectivity/aws/aws-databricks",
                        "docs/platform/secure/private-connectivity/aws/aws-redshift",
                        "docs/platform/secure/private-connectivity/aws/aws-postgres",
                        "docs/platform/secure/private-connectivity/aws/aws-teradata",
                        "docs/platform/secure/private-connectivity/aws/aws-self-hosted",
                        "docs/platform/secure/private-connectivity/aws/aws-ingress",
                      ],
                    },
                    {
                      type: "category",
                      label: "Azure",
                      link: { type: "doc", id: "docs/platform/secure/private-connectivity/azure/azure-overview" },
                      items: [
                        "docs/platform/secure/private-connectivity/azure/azure-overview",
                        "docs/platform/secure/private-connectivity/azure/azure-snowflake",
                        "docs/platform/secure/private-connectivity/azure/azure-databricks",
                        "docs/platform/secure/private-connectivity/azure/azure-postgres",
                        "docs/platform/secure/private-connectivity/azure/azure-synapse",
                        "docs/platform/secure/private-connectivity/azure/azure-fabric",
                        "docs/platform/secure/private-connectivity/azure/azure-teradata",
                        "docs/platform/secure/private-connectivity/azure/azure-self-hosted",
                      ],
                    },
                    {
                      type: "category",
                      label: "GCP",
                      link: { type: "doc", id: "docs/platform/secure/private-connectivity/gcp/gcp-overview" },
                      items: [
                        "docs/platform/secure/private-connectivity/gcp/gcp-overview",
                        "docs/platform/secure/private-connectivity/gcp/gcp-snowflake",
                        "docs/platform/secure/private-connectivity/gcp/gcp-bigquery",
                        "docs/platform/secure/private-connectivity/gcp/gcp-self-hosted",
                      ],
                    },
                  ],
                },
              ],
            }, // Network security
          ],
        },
        {
          type: "category",
          label: "dbt self-hosted installation",
          collapsed: true,
          link: { type: "doc", id: "docs/local/about-local" },
          items: [
            "docs/local/about-local",
            "docs/local/install-dbt",
            "docs/local/dbt-networking-requirements",
            "docs/local/configure-environment-variables",
            "docs/local/profiles.yml",
            "docs/local/connection-profiles",
            "docs/local/dbt-environments",
            {
              type: "category",
              label: "Connect to your data platform",
              link: {
                type: "doc",
                id: "docs/local/connect-data-platform/about-dbt-connections",
              },
              items: [
                "docs/local/connect-data-platform/about-dbt-connections",
                "docs/local/connect-data-platform/bigquery-setup",
                "docs/local/connect-data-platform/databricks-setup",
                "docs/local/connect-data-platform/redshift-setup",
                "docs/local/connect-data-platform/snowflake-setup",
                "docs/local/connect-data-platform/spark-setup",
                "docs/local/connect-data-platform/deltastream-setup",
                "docs/local/connect-data-platform/fabric-setup",
                "docs/local/connect-data-platform/fabricspark-setup",
                "docs/local/connect-data-platform/postgres-setup",
                "docs/local/connect-data-platform/alloydb-setup",
                "docs/local/connect-data-platform/lakebase-setup",
                "docs/local/connect-data-platform/trino-setup",
                "docs/local/connect-data-platform/hive-setup",
                "docs/local/connect-data-platform/impala-setup",
                "docs/local/connect-data-platform/athena-setup",
                "docs/local/connect-data-platform/glue-setup",
                "docs/local/connect-data-platform/clickhouse-setup",
                "docs/local/connect-data-platform/confluent-setup",
                "docs/local/connect-data-platform/cratedb-setup",
                "docs/local/connect-data-platform/databend-setup",
                "docs/local/connect-data-platform/decodable-setup",
                "docs/local/connect-data-platform/doris-setup",
                "docs/local/connect-data-platform/dremio-setup",
                "docs/local/connect-data-platform/duckdb-setup",
                "docs/local/connect-data-platform/exasol-setup",
                "docs/local/connect-data-platform/extrica-setup",
                "docs/local/connect-data-platform/firebolt-setup",
                "docs/local/connect-data-platform/greenplum-setup",
                "docs/local/connect-data-platform/ibm-db2-setup",
                "docs/local/connect-data-platform/ibmnetezza-setup",
                "docs/local/connect-data-platform/infer-setup",
                "docs/local/connect-data-platform/iomete-setup",
                "docs/local/connect-data-platform/layer-setup",
                "docs/local/connect-data-platform/materialize-setup",
                "docs/local/connect-data-platform/azuresynapse-setup",
                "docs/local/connect-data-platform/mssql-setup",
                "docs/local/connect-data-platform/mindsdb-setup",
                "docs/local/connect-data-platform/mysql-setup",
                "docs/local/connect-data-platform/oracle-setup",
                "docs/local/connect-data-platform/risingwave-setup",
                "docs/local/connect-data-platform/rockset-setup",
                "docs/local/connect-data-platform/sail-setup",
                "docs/local/connect-data-platform/singlestore-setup",
                "docs/local/connect-data-platform/sqlite-setup",
                "docs/local/connect-data-platform/starrocks-setup",
                "docs/local/connect-data-platform/teradata-setup",
                "docs/local/connect-data-platform/tidb-setup",
                "docs/local/connect-data-platform/upsolver-setup",
                "docs/local/connect-data-platform/vertica-setup",
                "docs/local/connect-data-platform/watsonx-presto-setup",
                "docs/local/connect-data-platform/watsonx-spark-setup",
                "docs/local/connect-data-platform/yellowbrick-setup",
                "docs/local/connect-data-platform/ydb-setup",
                "docs/local/connect-data-platform/maxcompute-setup",
                "docs/local/connect-data-platform/hologres-setup",
              ],
            },
          ],
        },
        "docs/running-a-dbt-project/run-your-dbt-projects",
        "docs/running-a-dbt-project/using-threads",
      ],
    },
    {
      type: 'html',
      value: 'AI and dbt',
      className: 'sidebar-title',
    },
        "docs/dbt-ai/about-dbt-ai",
        {
          type: "category",
          label: "dbt Wizard",
          collapsed: true,
          link: { type: "doc", id: "docs/platform/wizard-overview" },
          items: [
            "docs/platform/wizard-overview",
            "docs/dbt-ai/wizard-quickstart",
            "docs/platform/manage-dbt-ai",
            "docs/dbt-ai/wizard-use-cases",
            "docs/dbt-ai/wizard-how-it-works",
            "docs/dbt-ai/wizard-billing-faqs",
            {
              type: "category",
              label: "Pricing and billing",
              collapsed: true,
              link: { type: "doc", id: "docs/dbt-ai/pricing-billing/overview" },
              items: [
                "docs/dbt-ai/pricing-billing/overview",
                "docs/dbt-ai/pricing-billing/trial-and-billing",
              ],
            },
            {
              type: "category",
              label: "Wizard CLI",
              collapsed: true,
              link: { type: "doc", id: "docs/dbt-ai/wizard-cli" },
              items: [
                "docs/dbt-ai/wizard-cli",
                "docs/dbt-ai/wizard-byok",
                "docs/dbt-ai/wizard-skills",
                "docs/dbt-ai/wizard-subagents",
                "docs/dbt-ai/wizard-mcp",
                "docs/dbt-ai/wizard-headless",
                "docs/dbt-ai/wizard-migrate",
                "docs/dbt-ai/wizard-cli-reference",
                "docs/dbt-ai/wizard-slash-commands",
                "docs/dbt-ai/wizard-config",
                "docs/dbt-ai/wizard-telemetry",
              ],
            },
            {
              type: "category",
              label: "Wizard in platform",
              collapsed: true,
              link: { type: "doc", id: "docs/platform/wizard-platform" },
              items: [
                "docs/platform/wizard-platform",
                "docs/dbt-ai/wizard-ide",
                "docs/platform/wizard-home",
                "docs/platform/wizard-byok-platform",
                "docs/dbt-ai/wizard-platform-skills",
                "docs/dbt-ai/wizard-platform-mcp",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "dbt Copilot",
          collapsed: true,
          link: { type: "doc", id: "docs/dbt-ai/copilot-overview" },
          items: [
            "docs/dbt-ai/copilot-overview",
            "docs/dbt-ai/analyst-agent",
          ],
        },
    {
      type: "category",
      label: "dbt MCP server",
      collapsed: true,
      link: { type: "doc", id: "docs/dbt-ai/about-mcp", },
      items: [
        "docs/dbt-ai/about-mcp",
        "docs/dbt-ai/mcp-available-tools",
        {
          type: "category",
          label: "Get started",
          collapsed: true,
          link: { type: "doc", id: "docs/dbt-ai/mcp-quickstart-oauth" },
          items: [
            "docs/dbt-ai/mcp-quickstart-oauth",
            "docs/dbt-ai/mcp-quickstart-cli",
            "docs/dbt-ai/mcp-quickstart-remote",
          ],
        },
        {
          type: "category",
          label: "Setup and configuration",
          collapsed: true,
          items: [
            "docs/dbt-ai/setup-local-mcp",
            "docs/dbt-ai/setup-remote-mcp",
            "docs/dbt-ai/mcp-environment-variables",
            "docs/dbt-ai/mcp-find-ids",
          ],
        },
        {
          type: "category",
          label: "Integrations",
          collapsed: true,
          items: [
            "docs/dbt-ai/integrate-mcp-claude",
            "docs/dbt-ai/integrate-mcp-cursor",
            "docs/dbt-ai/integrate-mcp-vscode",
            "docs/dbt-ai/integrate-mcp-snowflake-cortex",
          ],
        },
        "docs/dbt-ai/mcp-troubleshooting",
      ],
    },
    "docs/dbt-ai/dbt-ai-faqs",
    {
      type: 'html',
      value: 'Build and develop',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Develop with dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/platform/about-develop-dbt" },
      items: [
        "docs/platform/about-develop-dbt",
        "docs/about-dbt-lsp",
        "docs/platform/about-defer",
        {
          type: "category",
          label: "dbt VS Code extension",
          collapsed: true,
          link: { type: "doc", id: "docs/about-dbt-extension" },
          items: [
            "docs/about-dbt-extension",
            "docs/dbt-extension-features",
            "docs/install-dbt-extension",
            "docs/upgrade-to-dbt-extension",
            "docs/sign-in-dbt-extension",
            "docs/configure-dbt-extension",
            "docs/dbt/vs-compare-changes",
          ],
        },
        {
          type: "category",
          label: "dbt platform CLI",
          collapsed: true,
          link: { type: "doc", id: "docs/platform/dbt-cli-installation" },
          items: [
            "docs/platform/dbt-cli-installation",
            "docs/platform/configure-dbt-cli",
          ],
        },
        {
          type: "category",
          label: "dbt Studio IDE",
          link: {
            type: "doc",
            id: "docs/platform/studio-ide/develop-in-studio",
          },
          items: [
            "docs/platform/studio-ide/develop-in-studio",
            "docs/platform/studio-ide/ide-user-interface",
            "docs/platform/studio-ide/keyboard-shortcuts",
            "docs/platform/studio-ide/git-commit-signing",
            "docs/platform/studio-ide/lint-format",
            "docs/platform/studio-ide/autofix-deprecations",
            "docs/platform/studio-ide/develop-studio-ai",
          ],
        },
        {
          type: "category",
          label: "dbt Canvas",
          collapsed: true,
          link: { type: "doc", id: "docs/platform/canvas" },
          items: [
            "docs/platform/canvas",
            "docs/platform/canvas-interface",
            "docs/platform/use-canvas",
            "docs/platform/build-canvas-copilot",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Build dbt projects",
      collapsed: true,
      link: { type: "doc", id: "docs/build/projects" },
      items: [
        "docs/build/projects",
        "docs/build/about-static-analysis",
        "docs/build/dbt-tips",
        {
          type: "category",
          label: "Build your DAG",
          collapsed: true,
          link: { type: "doc", id: "docs/build/models" },
          items: [
            {
              type: "category",
              label: "Models",
              link: { type: "doc", id: "docs/build/models" },
              items: [
                "docs/build/models",
                "docs/build/sql-models",
                "docs/build/python-models",
              ],
            },
            {
              type: "category",
              label: "Tests",
              link: { type: "doc", id: "docs/build/data-tests" },
              items: ["docs/build/data-tests", "docs/build/unit-tests"],
            },
            {
              type: "category",
              label: "Documentation",
              link: { type: "doc", id: "docs/build/documentation" },
              items: [
                "docs/build/documentation",
                "docs/build/view-documentation",
              ],
            },
            "docs/build/snapshots",
            "docs/build/seeds",
            "docs/build/jinja-macros",
            "docs/build/udfs",
            "docs/build/sources",
            "docs/build/exposures",
            "docs/build/groups",
            "docs/build/analyses",
          ],
        },
        {
          type: "category",
          label: "Build your metrics",
          link: { type: "doc", id: "docs/build/build-metrics-intro" },
          collapsed: true,
          items: [
            "docs/build/build-metrics-intro",
            "docs/build/latest-metrics-spec",
            {
              type: "link",
              label: "Quickstart with the dbt Semantic Layer",
              href: `/guides/sl-qs`,
            },
            "reference/semantic-layer-reference",
            {
              type: "category",
              label: "About MetricFlow",
              link: { type: "doc", id: "docs/build/about-metricflow" },
              items: [
                "docs/build/about-metricflow",
                "docs/build/join-logic",
                "docs/build/metricflow-time-spine",
                "docs/build/metricflow-commands",
                "docs/build/validation",
              ],
            },
            {
              type: "category",
              label: "Semantic models",
              link: { type: "doc", id: "docs/build/semantic-models" },
              items: [
                "docs/build/semantic-models",
                "docs/build/dimensions",
                "docs/build/entities",
                "docs/build/measures",
                "docs/build/ossie-semantic-models",
              ],
            },
            {
              type: "category",
              label: "Metrics",
              link: { type: "doc", id: "docs/build/metrics-overview" },
              items: [
                "docs/build/metrics-overview",
                "docs/build/conversion",
                "docs/build/cumulative",
                "docs/build/derived",
                "docs/build/ratio",
                "docs/build/simple",
              ],
            },
            "docs/build/saved-queries",
            {
              type: "category",
              label: "Advanced data modeling",
              link: { type: "doc", id: "docs/build/advanced-topics" },
              items: [
                "docs/build/fill-nulls-advanced",
                "docs/build/ref-metrics-in-filters",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Enhance your models",
          collapsed: true,
          link: { type: "doc", id: "docs/build/enhance-your-models" },
          items: [
            "docs/build/enhance-your-models",
            "docs/build/materializations",
            {
              type: "category",
              label: "Incremental models",
              link: {
                type: "doc",
                id: "docs/build/incremental-models-overview",
              },
              items: [
                "docs/build/incremental-models-overview",
                "docs/build/incremental-models",
                "docs/build/incremental-strategy",
                "docs/build/incremental-microbatch",
                "docs/build/parallel-batch-execution",
              ],
            },
            {
              type: "category",
              label: "Apache Iceberg",
              collapsed: true,
              link: {
                type: "doc",
                id: "docs/build/iceberg/apache-iceberg-support",
              },
              items: [
                "docs/build/iceberg/apache-iceberg-support",
                "docs/build/iceberg/about-catalogs",
                "docs/build/iceberg/catalogs-yml",
                "docs/build/iceberg/adapters/snowflake-iceberg-support",
                "docs/build/iceberg/adapters/databricks-iceberg-support",
                "docs/build/iceberg/adapters/bigquery-iceberg-support",
                "docs/build/iceberg/adapters/duckdb-iceberg-support",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Enhance your code",
          collapsed: true,
          link: { type: "doc", id: "docs/build/enhance-your-code" },
          items: [
            "docs/build/enhance-your-code",
            "docs/build/environment-variables",
            "docs/build/hooks-operations",
            "docs/build/packages",
            "docs/build/project-variables",
          ],
        },
        {
          type: "category",
          label: "Organize your outputs",
          collapsed: true,
          link: { type: "doc", id: "docs/build/organize-your-outputs" },
          items: [
            "docs/build/organize-your-outputs",
            "docs/build/custom-schemas",
            "docs/build/custom-databases",
            "docs/build/custom-aliases",
            "docs/build/custom-target-names",
          ],
        },
        {
          type: "category",
          label: "Optimize development",
          collapsed: true,
          link: { type: "doc", id: "docs/build/empty-flag" },
          items: ["docs/build/empty-flag", "docs/build/sample-flag"],
        },
        //"docs/building-a-dbt-project/dont-nest-your-curlies",
        //"docs/building-a-dbt-project/archival",
      ],
    },
    {
      type: "category",
      label: "Build dbt Mesh",
      link: { type: "doc", id: "docs/mesh/about-mesh" },
      items: [
        "docs/mesh/about-mesh",
        "docs/mesh/cross-platform-mesh",
        {
          type: "category",
          label: "Model governance",
          collapsed: true,
          link: {
            type: "doc",
            id: "docs/mesh/govern/about-model-governance",
          },
          items: [
            "docs/mesh/govern/about-model-governance",
            "docs/mesh/govern/model-access",
            "docs/mesh/govern/model-contracts",
            "docs/mesh/govern/model-versions",
            "docs/mesh/govern/project-dependencies",
          ],
        },
      ],
    },
    {
      type: 'html',
      value: 'Deploy and explore',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Deploy dbt",
      collapsed: true,
      link: { type: "doc", id: "docs/deploy/deployments" },
      items: [
        "docs/deploy/deployments",
        "docs/deploy/job-scheduler",
        "docs/deploy/deploy-environments",
        {
          type: "category",
          label: "Continuous integration",
          collapsed: true,
          link: { type: "doc", id: "docs/deploy/about-ci" },
          items: [
            "docs/deploy/about-ci",
            "docs/deploy/continuous-integration",
            "docs/deploy/advanced-ci",
          ],
        },
        "docs/deploy/continuous-deployment",
        {
          type: "category",
          label: "Jobs",
          link: { type: "doc", id: "docs/deploy/jobs" },
          items: [
            "docs/deploy/jobs",
            "docs/deploy/deploy-jobs",
            "docs/deploy/ci-jobs",
            "docs/deploy/merge-jobs",
            "docs/deploy/job-commands",
          ],
        },
        {
          type: "category",
          label: "Monitor jobs and alerts",
          link: { type: "doc", id: "docs/deploy/monitor-jobs" },
          items: [
            "docs/deploy/monitor-jobs",
            "docs/deploy/orchestrate-exposures",
            "docs/deploy/artifacts",
            "docs/deploy/job-notifications",
            "docs/deploy/model-notifications",
            "docs/deploy/run-visibility",
            "docs/deploy/retry-jobs",
            "docs/deploy/source-freshness",
            "docs/deploy/webhooks",
          ],
        },
        {
          type: "category",
          label: "Hybrid projects",
          collapsed: true,
          link: { type: "doc", id: "docs/deploy/hybrid-projects" },
          items: ["docs/deploy/hybrid-projects", "docs/deploy/hybrid-setup"],
        },
        "docs/deploy/deployment-tools",
      ],
    }, // end of "Deploy dbt"
    {
      type: "category",
      label: "Optimize builds with dbt State",
      link: { type: "doc", id: "docs/deploy/dbt-state-about" },
      items: [
        "docs/deploy/dbt-state-about",
        {
          type: "category",
          label: "Set up dbt State",
          link: { type: "doc", id: "docs/deploy/dbt-state-setup" },
          items: [
            "docs/deploy/dbt-state-setup", 
            "docs/deploy/dbt-state-enable-jobs", 
            "docs/deploy/dbt-state-enable-studio", 
            "docs/deploy/dbt-state-cicd", 
            "docs/deploy/dbt-state-deferral",
          ],
        },
        "docs/deploy/dbt-state-trial",
        "docs/deploy/dbt-state-examples",
        "docs/deploy/dbt-state-interface",
        "docs/deploy/dbt-state-migration",
      ],
    },
    {
      type: "category",
      label: "Explore your data",
      link: { type: "doc", id: "docs/explore/explore-your-data" },
      items: [
        "docs/explore/explore-your-data",
        {
          type: "category",
          label: "Track costs and optimizations with Cost Insights",
          link: {
            type: "doc",
            id: "docs/explore/cost-insights",
          },
          items: [
            "docs/explore/cost-insights",
            "docs/explore/set-up-cost-insights",
            "docs/explore/explore-cost-data",
          ],
        },
        {
          type: "category",
          label: "Discover data with dbt Catalog",
          link: { type: "doc", id: "docs/explore/explore-projects" },
          items: [
            "docs/explore/explore-projects",
            "docs/explore/access-from-dbt-platform",
            "docs/explore/column-level-lineage",
            "docs/explore/data-health-signals",
            "docs/explore/explore-multiple-projects",
            "docs/explore/global-navigation",
            "docs/explore/model-performance",
            "docs/explore/project-recommendations",
            "docs/explore/dbt-explorer-faqs",
            {
              type: "category",
              label: "Model consumption",
              link: {
                type: "doc",
                id: "docs/explore/view-downstream-exposures",
              },
              items: [
                "docs/explore/view-downstream-exposures",
                "docs/explore/data-tile",
                "docs/explore/model-query-history",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Analyze with dbt Insights",
          link: { type: "doc", id: "docs/explore/dbt-insights" },
          items: [
            "docs/explore/dbt-insights", // main query page doc
            "docs/explore/navigate-dbt-insights", // navigate query page doc
            "docs/explore/access-dbt-insights", // info on how to access and use query page
          ],
        },
        {
          type: "category",
          label: "Document your projects",
          link: {
            type: "doc",
            id: "docs/explore/build-and-view-your-docs",
          },
          items: ["docs/explore/build-and-view-your-docs"],
        },
      ],
    },
    {
      type: "category",
      label: "Use the dbt Semantic Layer",
      collapsed: true,
      link: { type: "doc", id: "docs/use-dbt-semantic-layer/dbt-sl" },
      items: [
        "docs/use-dbt-semantic-layer/dbt-sl",
        {
          type: "link",
          label: "Quickstart with the dbt Semantic Layer",
          href: `/guides/sl-qs`,
        },
        {
          type: "category",
          label: "Configure",
          link: { type: "doc", id: "docs/use-dbt-semantic-layer/setup-sl" },
          items: [
            "docs/use-dbt-semantic-layer/setup-sl",
            "docs/use-dbt-semantic-layer/sl-architecture",
          ],
        },
        {
          type: "category",
          label: "Deploy metrics",
          link: { type: "doc", id: "docs/use-dbt-semantic-layer/deploy-sl" },
          items: [
            "docs/use-dbt-semantic-layer/deploy-sl",
            "docs/use-dbt-semantic-layer/exports",
            "docs/use-dbt-semantic-layer/sl-cache",
          ],
        },
        {
          type: "category",
          label: "Consume",
          link: {
            type: "doc",
            id: "docs/use-dbt-semantic-layer/consume-metrics",
          },
          items: ["docs/use-dbt-semantic-layer/consume-metrics"],
        },
        "docs/use-dbt-semantic-layer/sl-faqs",
      ],
    },
    {
      type: 'html',
      value: 'Additional tools',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "dbt integrations",
      link: { type: "doc", id: "docs/platform-integrations/overview" },
      items: [
        "docs/platform-integrations/overview",
        {
          type: "category",
          label: "Visualize and orchestrate exposures",
          link: {
            type: "doc",
            id: "docs/platform-integrations/downstream-exposures",
          },
          items: [
            "docs/platform-integrations/downstream-exposures",
            "docs/platform-integrations/downstream-exposures-tableau",
            "docs/platform-integrations/orchestrate-exposures",
          ],
        },
        {
          type: "category",
          label: "Semantic Layer integrations",
          link: {
            type: "doc",
            id: "docs/platform-integrations/avail-sl-integrations",
          },
          items: [
            "docs/platform-integrations/avail-sl-integrations",
            "docs/platform-integrations/semantic-layer/gsheets",
            "docs/platform-integrations/semantic-layer/excel",
            "docs/platform-integrations/semantic-layer/power-bi",
            "docs/platform-integrations/semantic-layer/tableau",
          ],
        },
      ],
    },
    {
      type: 'html',
      value: 'Release information',
      className: 'sidebar-title',
    },
    {
      type: "category",
      label: "Available dbt versions",
      link: { type: "doc", id: "docs/dbt-versions/about-versions" },
      items: [
        "docs/dbt-versions/about-versions",
        "docs/dbt-versions/dbt-versions",
        "docs/dbt-versions/dbt-version-compatibility",
        "docs/dbt-versions/dbt-release-tracks",
        "docs/dbt-versions/upgrade-dbt-platform-version",
        "docs/dbt-versions/product-lifecycles",
        "docs/dbt-versions/experimental-features",
        {
          type: "category",
          label: "dbt version upgrade guides",
          link: {
            type: "generated-index",
            title: "Version upgrade guides",
            description: "Learn what's new in the latest version of dbt.",
            slug: "/docs/dbt-versions/dbt-upgrade",
          },
          items: [
            "docs/dbt/dbt-readiness",
            {
              type: "autogenerated",
              dirName: "docs/dbt-versions/dbt-upgrade",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "dbt release notes",
      link: {
        type: "doc",
        id: "docs/dbt-versions/release-notes",
      },
      items: [
        "docs/dbt-versions/release-notes",
        "docs/dbt-versions/dbt-platform-release-notes-gen",
        "docs/dbt-versions/compatible-track-changelog",
        "docs/dbt-versions/2025-release-notes",
        "docs/dbt-versions/2024-release-notes",
        "docs/dbt-versions/2023-release-notes",
        "docs/dbt-versions/2022-release-notes",
        {
          type: "autogenerated",
          dirName: "docs/dbt-versions/release-notes",
        },
      ],
    },
    {
      type: 'html',
      value: ' ',
      className: 'sidebar-title',
    },
  ],
  apis: [
    "docs/dbt-apis/overview",
    "docs/dbt-apis/rate-limits",
    {
      type: "category",
      label: "API Access",
      link: { type: "doc", id: "docs/dbt-apis/authentication" },
      items: [
        "docs/dbt-apis/authentication",
        "docs/dbt-apis/user-tokens",
        "docs/dbt-apis/service-tokens",
      ],
    },
    {
      type: "category",
      label: "Administrative API",
      link: { type: "doc", id: "docs/dbt-apis/admin-api" },
      items: [
        "docs/dbt-apis/admin-api",
        {
          type: "link",
          label: "API v2",
          href: "/dbt-cloud/api-v2",
        },
        {
          type: "link",
          label: "API v3",
          href: "/dbt-cloud/api-v3",
        },
      ],
    },
    {
      type: "category",
      label: "Discovery API",
      link: { type: "doc", id: "docs/dbt-apis/discovery-api" },
      items: [
        "docs/dbt-apis/discovery-api",
        "docs/dbt-apis/discovery-use-cases-and-examples",
        "docs/dbt-apis/project-state",
        "docs/dbt-apis/discovery-querying",
        {
          type: "category",
          label: "Schema",
          link: {
            type: "doc",
            id: "docs/dbt-apis/discovery-schema-about",
          },
          items: [
            "docs/dbt-apis/discovery-schema-about",
            {
              type: "category",
              label: "Environment (recommended)",
              link: {
                type: "doc",
                id: "docs/dbt-apis/discovery-schema-environment",
              },
              items: [
                "docs/dbt-apis/discovery-schema-environment",
                {
                  type: "category",
                  label: "Applied",
                  link: {
                    type: "doc",
                    id: "docs/dbt-apis/discovery-schema-environment-applied",
                  },
                  items: [
                    "docs/dbt-apis/discovery-schema-environment-applied",
                    "docs/dbt-apis/discovery-schema-environment-applied-tests",
                    "docs/dbt-apis/discovery-schema-environment-applied-sources",
                    "docs/dbt-apis/discovery-schema-environment-applied-snapshots",
                    "docs/dbt-apis/discovery-schema-environment-applied-seeds",
                    "docs/dbt-apis/discovery-schema-environment-applied-resources",
                    "docs/dbt-apis/discovery-schema-environment-applied-models",
                    "docs/dbt-apis/discovery-schema-environment-applied-exposures",
                    "docs/dbt-apis/discovery-schema-environment-applied-exposure-tile",
                    "docs/dbt-apis/discovery-schema-environment-applied-tags",
                    "docs/dbt-apis/discovery-schema-environment-applied-packages",
                    "docs/dbt-apis/discovery-schema-environment-applied-owners",
                    "docs/dbt-apis/discovery-schema-environment-applied-modelHistoricalRuns",
                    "docs/dbt-apis/discovery-schema-environment-applied-lineage",
                  ],
                },
                "docs/dbt-apis/discovery-schema-environment-definition",
              ],
            },
            // Uncomment to add Definition subpage, but need to make items non-empty
            // {
            //   type: "category",
            //   label: "Definition",
            //   items: [
            //     // insert pages here
            //   ],
            // },
            {
              type: "category",
              label: "Job",
              link: {
                type: "doc",
                id: "docs/dbt-apis/discovery-schema-job",
              },
              items: [
                "docs/dbt-apis/discovery-schema-job",
                "docs/dbt-apis/discovery-schema-job-model",
                "docs/dbt-apis/discovery-schema-job-models",
                "docs/dbt-apis/discovery-schema-job-source",
                "docs/dbt-apis/discovery-schema-job-sources",
                "docs/dbt-apis/discovery-schema-job-seed",
                "docs/dbt-apis/discovery-schema-job-seeds",
                // "docs/dbt-apis/discovery-schema-job-snapshot",
                "docs/dbt-apis/discovery-schema-job-snapshots",
                "docs/dbt-apis/discovery-schema-job-test",
                "docs/dbt-apis/discovery-schema-job-tests",
                "docs/dbt-apis/discovery-schema-job-exposure",
                "docs/dbt-apis/discovery-schema-job-exposures",
                // "docs/dbt-apis/discovery-schema-job-macro",
                // "docs/dbt-apis/discovery-schema-job-macros",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Semantic Layer APIs",
      link: { type: "doc", id: "docs/dbt-apis/sl-api-overview" },
      items: [
        "docs/dbt-apis/sl-api-overview",
        "docs/dbt-apis/sl-graphql",
        "docs/dbt-apis/sl-jdbc",
        "docs/dbt-apis/sl-python",
      ],
    },
  ],
  reference: [
    "reference/references-overview",
    {
      type: "category",
      label: "Project configs",
      link: {
        type: "generated-index",
        title: "Project configs",
        description: "The list of project configs available in dbt.",
      },
      collapsed: true,
      items: [
        "reference/dbt_project.yml",
        "reference/dbt_cloud.yml",
        "reference/dbtignore",
        "reference/project-configs/analysis-paths",
        "reference/project-configs/asset-paths",
        "reference/project-configs/clean-targets",
        "reference/project-configs/config-version",
        "reference/project-configs/dispatch-config",
        "reference/project-configs/docs-paths",
        "reference/project-configs/function-paths",
        "reference/project-configs/macro-paths",
        "reference/project-configs/name",
        "reference/project-configs/on-run-start-on-run-end",
        "reference/project-configs/osi-paths",
        "reference/project-configs/packages-install-path",
        "reference/project-configs/profile",
        "reference/project-configs/query-comment",
        "reference/project-configs/quoting",
        "reference/project-configs/require-dbt-version",
        "reference/project-configs/snapshot-paths",
        "reference/project-configs/seed-paths",
        "reference/project-configs/model-paths",
        "reference/project-configs/test-paths",
        "reference/project-configs/version",
      ],
    },
    {
      type: "category",
      label: "Platform-specific configs",
      link: {
        type: "generated-index",
        title: "Platform-specific configs",
        description:
          "Platform-specific configs are used to configure the dbt project for a specific database platform.",
        slug: "/reference/resource-configs",
      },
      items: [
        "reference/resource-configs/azuresynapse-configs",
        "reference/resource-configs/athena-configs",
        "reference/resource-configs/impala-configs",
        "reference/resource-configs/spark-configs",
        "reference/resource-configs/bigquery-configs",
        "reference/resource-configs/bigquery-function-support",
        "reference/resource-configs/clickhouse-configs",
        "reference/resource-configs/confluent-configs",
        "reference/resource-configs/databricks-configs",
        "reference/resource-configs/deltastream-configs",
        "reference/resource-configs/doris-configs",
        "reference/resource-configs/duckdb-configs",
        "reference/resource-configs/exasol-configs",
        "reference/resource-configs/fabric-configs",
        "reference/resource-configs/fabricspark-configs",
        "reference/resource-configs/firebolt-configs",
        "reference/resource-configs/greenplum-configs",
        "reference/resource-configs/hive-configs",
        "reference/resource-configs/ibm-db2-config",
        "reference/resource-configs/ibm-netezza-config",
        "reference/resource-configs/infer-configs",
        "reference/resource-configs/materialize-configs",
        "reference/resource-configs/mssql-configs",
        "reference/resource-configs/mindsdb-configs",
        "reference/resource-configs/oracle-configs",
        "reference/resource-configs/postgres-configs",
        "reference/resource-configs/redshift-configs",
        "reference/resource-configs/singlestore-configs",
        "reference/resource-configs/snowflake-configs",
        "reference/resource-configs/snowflake-function-support",
        "reference/resource-configs/trino-configs",
        "reference/resource-configs/starrocks-configs",
        "reference/resource-configs/teradata-configs",
        "reference/resource-configs/upsolver-configs",
        "reference/resource-configs/vertica-configs",
        "reference/resource-configs/watsonx-presto-config",
        "reference/resource-configs/watsonx-spark-config",
        "reference/resource-configs/yellowbrick-configs",
      ],
    },
    {
      type: "category",
      label: "Resource configs and properties",
      link: { type: "doc", id: "reference/resource-configs/resource-path" },
      items: [
        "reference/resource-configs/resource-path",
        {
          type: "category",
          label: "Configs and properties",
          link: {
            type: "doc",
            id: "reference/configs-and-properties",
          },
          items: [
            "reference/configs-and-properties",
            "reference/define-configs",
            "reference/define-properties",
          ],
        },
        {
          type: "category",
          label: "General properties",
          link: {
            type: "generated-index",
            title: "General properties",
            description: "The list of general properties available in dbt.",
          },
          items: [
            "reference/resource-properties/anchors",
            "reference/resource-properties/columns",
            "reference/resource-properties/config",
            "reference/resource-properties/constraints",
            "reference/resource-properties/deprecation_date",
            "reference/resource-properties/description",
            "reference/resource-properties/latest_version",
            "reference/resource-properties/data-tests",
            "reference/resource-properties/versions",
          ],
        },
        {
          type: "category",
          label: "General configs",
          link: {
            type: "generated-index",
            title: "General configs",
            description: "The list of general configs available in dbt.",
          },
          items: [
            "reference/advanced-config-usage",
            "reference/resource-configs/access",
            "reference/resource-configs/alias",
            "reference/resource-configs/database",
            "reference/resource-configs/docs",
            "reference/resource-configs/enabled",
            "reference/resource-configs/event-time",
            "reference/resource-configs/full_refresh",
            "reference/resource-configs/grants",
            "reference/resource-configs/group",
            "reference/resource-configs/meta",
            "reference/resource-configs/persist_docs",
            "reference/resource-configs/plus-prefix",
            "reference/resource-configs/pre-hook-post-hook",
            "reference/resource-configs/schema",
            "reference/resource-configs/static-analysis",
            "reference/resource-configs/tags",
            "reference/resource-configs/unique_key",
          ],
        },
        {
          type: "category",
          label: "For models",
          link: { type: "doc", id: "reference/model-properties" },
          items: [
            "reference/model-properties",
            "reference/model-configs",
            "reference/resource-configs/freshness",
            "reference/resource-configs/batch-size",
            "reference/resource-configs/begin",
            "reference/resource-properties/concurrent_batches",
            "reference/resource-configs/contract",
            "reference/resource-configs/latest_version_pointer",
            "reference/resource-configs/lookback",
            "reference/resource-configs/materialized",
            "reference/resource-properties/model_name",
            "reference/resource-configs/on_configuration_change",
            "reference/resource-configs/on_error",
            "reference/resource-configs/sql_header",
          ],
        },
        {
          type: "category",
          label: "For dbt State",
          link: { type: "doc", id: "reference/resource-configs/dbt-state-configs" },
          items: [
            "reference/resource-configs/dbt-state-configs",
            "reference/resource-configs/lag-tolerance",
            "reference/resource-configs/compare-unrendered-code",
            "reference/resource-configs/require-fresh-data-from",
            "reference/resource-configs/evaluate-volatile-sql",
            "reference/resource-configs/pre-clone",
            "reference/resource-configs/execute-hooks-on-any-reuse",
            "reference/resource-configs/defer-to-target",
            "reference/resource-configs/allow-clones",
            "reference/resource-configs/metadata-warehouse",
          ],
        },
        {
          type: "category",
          label: "For seeds",
          link: { type: "doc", id: "reference/seed-properties" },
          items: [
            "reference/seed-properties",
            "reference/seed-configs",
            "reference/resource-configs/column_types",
            "reference/resource-configs/delimiter",
            "reference/resource-configs/quote_columns",
          ],
        },
        {
          type: "category",
          label: "For snapshots",
          link: { type: "doc", id: "reference/snapshot-properties" },
          items: [
            "reference/snapshot-properties",
            "reference/snapshot-configs",
            "reference/resource-configs/snapshots-jinja-legacy",
            "reference/resource-configs/check_cols",
            "reference/resource-configs/dbt_valid_to_current",
            "reference/resource-configs/hard-deletes",
            "reference/resource-configs/invalidate_hard_deletes",
            "reference/resource-configs/snapshot_meta_column_names",
            "reference/resource-configs/snapshot_name",
            "reference/resource-configs/strategy",
            "reference/resource-configs/target_database",
            "reference/resource-configs/target_schema",
            "reference/resource-configs/updated_at",
          ],
        },
        {
          type: "category",
          label: "For data tests",
          link: { type: "doc", id: "reference/data-test-configs" },
          items: [
            "reference/data-test-configs",
            "reference/resource-configs/fail_calc",
            "reference/resource-configs/limit",
            "reference/resource-configs/severity",
            "reference/resource-configs/store_failures",
            "reference/resource-configs/store_failures_as",
            "reference/resource-configs/where",
          ],
        },
        {
          type: "category",
          label: "For unit tests",
          link: { type: "doc", id: "reference/resource-properties/unit-tests" },
          items: [
            "reference/resource-properties/unit-tests",
            "reference/resource-properties/unit-test-input",
            "reference/resource-properties/data-formats",
            "reference/resource-properties/data-types",
            "reference/resource-properties/unit-testing-versions",
            "reference/resource-properties/unit-test-overrides",
          ],
        },
        {
          type: "category",
          label: "For sources",
          link: { type: "doc", id: "reference/source-properties" },
          items: [
            "reference/source-properties",
            "reference/source-configs",
            "reference/resource-properties/database",
            "reference/resource-properties/external",
            "reference/resource-properties/freshness",
            "reference/resource-properties/identifier",
            "reference/resource-properties/loader",
            "reference/resource-properties/quoting",
            "reference/resource-properties/schema",
            "reference/resource-properties/overrides",
          ],
        },
        {
          type: "category",
          label: "For analyses",
          link: { type: "doc", id: "reference/analysis-properties" },
          items: ["reference/analysis-properties"],
        },
        {
          type: "category",
          label: "For exposures",
          link: { type: "doc", id: "reference/exposure-properties" },
          items: ["reference/exposure-properties"],
        },
        {
          type: "category",
          label: "For macros",
          link: { type: "doc", id: "reference/macro-properties" },
          items: [
            "reference/macro-properties",
            "reference/resource-properties/arguments",
          ],
        },
        {
          type: "category",
          label: "For semantic models",
          link: { type: "doc", id: "reference/semantic-model-properties" },
          items: ["reference/semantic-model-properties"],
        },
        {
          type: "category",
          label: "For metrics",
          link: { type: "doc", id: "reference/metric-properties" },
          items: ["reference/metric-properties"],
        },
        {
          type: "category",
          label: "For dimensions",
          link: { type: "doc", id: "reference/dimension-properties" },
          items: ["reference/dimension-properties"],
        },
        {
          type: "category",
          label: "For functions",
          link: { type: "doc", id: "reference/function-properties" },
          items: [
            "reference/function-properties",
            "reference/function-configs",
            "reference/resource-configs/type",
            "reference/resource-configs/volatility",
            "reference/resource-configs/runtime-version",
            "reference/resource-configs/entry-point",
            "reference/resource-configs/packages",
            "reference/resource-configs/quote_args",
            "reference/resource-properties/returns",
            "reference/resource-properties/function-arguments",
            "reference/resource-properties/overloads",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Commands",
      link: { type: "doc", id: "reference/dbt-commands" },
      items: [
        "reference/dbt-commands",
        {
          type: "category",
          label: "List of commands",
          link: {
            type: "generated-index",
            title: "List of commands",
            description: "The list of commands available in dbt.",
          },
          items: [
            "reference/commands/build",
            "reference/commands/clean",
            "reference/commands/clone",
            "reference/commands/cmd-docs",
            "reference/commands/compile",
            "reference/commands/debug",
            "reference/commands/deps",
            "reference/commands/dbt-environment",
            "reference/commands/freshness",
            "reference/commands/init",
            "reference/commands/invocation",
            "reference/commands/lint",
            "reference/commands/list",
            "reference/commands/login",
            "reference/commands/parse",
            "reference/commands/retry",
            "reference/commands/rpc",
            "reference/commands/run",
            "reference/commands/run-operation",
            "reference/commands/seed",
            "reference/commands/show",
            "reference/commands/snapshot",
            "reference/commands/source",
            "reference/commands/state-explain",
            "reference/commands/system",
            "reference/commands/test",
            "reference/commands/version",
          ],
        },
        {
          type: "category",
          label: "Node selection",
          link: { type: "doc", id: "reference/node-selection/syntax" },
          items: [
            "reference/node-selection/syntax",
            "reference/node-selection/exclude",
            "reference/node-selection/defer",
            "reference/node-selection/graph-operators",
            "reference/node-selection/set-operators",
            "reference/node-selection/methods",
            "reference/node-selection/putting-it-together",
            "reference/node-selection/yaml-selectors",
            "reference/node-selection/test-selection-examples",
            {
              type: "category",
              label: "About state selection",
              link: {
                type: "doc",
                id: "reference/node-selection/state-selection",
              },
              items: [
                "reference/node-selection/state-selection",
                "reference/node-selection/configure-state",
                "reference/node-selection/state-comparison-caveats",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Flags (global configs)",
          link: {
            type: "doc",
            id: "reference/global-configs/about-global-configs",
          },
          items: [
            "reference/global-configs/about-global-configs",
            {
              type: "category",
              label: "Behavior changes",
              link: {
                type: "doc",
                id: "reference/global-configs/behavior-changes",
              },
              items: [
                "reference/global-configs/behavior-changes",
                {
                  type: "category",
                  label: "Behavior change flags",
                  link: {
                    type: "generated-index",
                    title: "Behavior change flags",
                    description: "Reference documentation for each dbt behavior change flag.",
                  },
                  items: [
                    "reference/global-configs/behavior-flags/allow_jinja_file_extensions",
                    "reference/global-configs/behavior-flags/enable_truthy_nulls_equals_macro",
                    "reference/global-configs/behavior-flags/latest_version_pointer_enabled_by_default",
                    "reference/global-configs/behavior-flags/require_all_warnings_handled_by_warn_error",
                    "reference/global-configs/behavior-flags/require_batched_execution_for_custom_microbatch_strategy",
                    "reference/global-configs/behavior-flags/require_corrected_analysis_fqns",
                    "reference/global-configs/behavior-flags/require_explicit_package_overrides_for_builtin_materializations",
                    "reference/global-configs/behavior-flags/require_generic_test_arguments_property",
                    "reference/global-configs/behavior-flags/require_nested_cumulative_type_params",
                    "reference/global-configs/behavior-flags/require_ref_searches_node_package_before_root",
                    "reference/global-configs/behavior-flags/require_resource_names_without_plus_prefix",
                    "reference/global-configs/behavior-flags/require_resource_names_without_spaces",
                    "reference/global-configs/behavior-flags/require_source_and_semantic_model_names_without_spaces",
                    "reference/global-configs/behavior-flags/require_sql_header_in_test_configs",
                    "reference/global-configs/behavior-flags/require_unique_project_resource_names",
                    "reference/global-configs/behavior-flags/require_valid_schema_from_generate_schema_name",
                    "reference/global-configs/behavior-flags/require_yaml_configuration_for_mf_time_spines",
                    "reference/global-configs/behavior-flags/skip_nodes_if_on_run_start_fails",
                    "reference/global-configs/behavior-flags/source_freshness_run_project_hooks",
                    "reference/global-configs/behavior-flags/state_modified_compare_more_unrendered_values",
                    "reference/global-configs/behavior-flags/validate_macro_args",
                  ],
                },
                {
                  type: "category",
                  label: "Adapter behavior change flags",
                  link: {
                    type: "doc",
                    id: "reference/global-configs/adapter-behavior-changes",
                  },
                  items: [
                    "reference/global-configs/adapter-behavior-changes",
                    "reference/global-configs/bigquery-changes",
                    "reference/global-configs/databricks-changes",
                    "reference/global-configs/redshift-changes",
                    "reference/global-configs/snowflake-changes",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Setting flags",
              link: {
                type: "generated-index",
                title: "Setting flags",
                description: "The flags you can set to configure dbt.",
              },
              items: [
                "reference/global-configs/command-line-options",
                "reference/global-configs/environment-variable-configs",
                "reference/global-configs/project-flags",
                "reference/global-configs/user-settings",
              ],
            },
            {
              type: "category",
              label: "Available flags",
              link: {
                type: "generated-index",
                title: "Available flags",
                description: "The list of flags available in dbt.",
              },
              items: [
                "reference/global-configs/usage-stats",
                "reference/global-configs/version-compatibility",
                "reference/global-configs/logs",
                "reference/global-configs/cache",
                "reference/global-configs/failing-fast",
                "reference/global-configs/indirect-selection",
                "reference/global-configs/json-artifacts",
                "reference/global-configs/parsing",
                "reference/global-configs/sqlparse",
                "reference/global-configs/print-output",
                "reference/global-configs/record-timing-info",
                "reference/global-configs/resource-type",
                "reference/global-configs/static-analysis-flag",
                "reference/global-configs/warnings",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Deprecations & warnings",
          link: {
            type: "doc",
            id: "reference/changes-overview",
          },
          items: [
            "reference/changes-overview",
            "reference/deprecations",
          ],
        },
        "reference/events-logging",
        "reference/telemetry-observability",
        "reference/exit-codes",
        "reference/parsing",
        "reference/programmatic-invocations",
      ],
    },
    {
      type: "category",
      label: "Jinja reference",
      link: {
        type: "generated-index",
        title: "Jinja reference",
        description: "The list of Jinja functions and context variables available in dbt.",
      },
      items: [
        {
          type: "category",
          label: "dbt Jinja context functions",
          link: {
            type: "generated-index",
            title: "dbt Jinja functions and context variables",
            description:
              "In addition to the standard Jinja library, we've added additional functions and variables to the Jinja context that are useful when working with a dbt project. Note that dependencies.yml is not Jinja rendered and therefore does not support Jinja.",
            slug: "/reference/dbt-jinja-functions-context-variables",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "reference/dbt-jinja-functions",
            },
          ],
        },
        "reference/dbt-classes",
      ],
    },
    {
      type: "category",
      label: "dbt Artifacts",
      link: { type: "doc", id: "reference/artifacts/dbt-artifacts" },
      items: [
        "reference/artifacts/dbt-artifacts",
        "reference/artifacts/catalog-json",
        "reference/artifacts/manifest-json",
        "reference/artifacts/run-results-json",
        "reference/artifacts/sources-json",
        "reference/artifacts/freshness-json",
        "reference/artifacts/sl-manifest",
        "reference/artifacts/other-artifacts",
      ],
    },
    {
      type: "category",
      label: "Database Permissions",
      link: {
        type: "doc",
        id: "reference/database-permissions/about-database-permissions",
      },
      items: [
        "reference/database-permissions/about-database-permissions",
        "reference/database-permissions/databricks-permissions",
        "reference/database-permissions/postgres-permissions",
        "reference/database-permissions/redshift-permissions",
        "reference/database-permissions/snowflake-permissions",
      ],
    },
  ],
  bestpractices: [
    {
      type: "category",
      label: "Best practices",
      link: {
        type: "generated-index",
        title: "Best practice guides",
        description:
          "Learn how dbt Labs approaches building projects through our current viewpoints on structure, style, and setup.",
        slug: "best-practices",
      },
      items: [
        {
          type: "category",
          label: "How we structure our dbt projects",
          link: {
            type: "doc",
            id: "best-practices/how-we-structure/1-guide-overview",
          },
          items: [
            "best-practices/how-we-structure/2-staging",
            "best-practices/how-we-structure/3-intermediate",
            "best-practices/how-we-structure/4-marts",
            "best-practices/how-we-structure/5-the-rest-of-the-project",
          ],
        },
        {
          type: "category",
          label: "How we style our dbt projects",
          link: {
            type: "doc",
            id: "best-practices/how-we-style/0-how-we-style-our-dbt-projects",
          },
          items: [
            "best-practices/how-we-style/1-how-we-style-our-dbt-models",
            "best-practices/how-we-style/2-how-we-style-our-sql",
            "best-practices/how-we-style/3-how-we-style-our-python",
            "best-practices/how-we-style/4-how-we-style-our-jinja",
            "best-practices/how-we-style/5-how-we-style-our-yaml",
            "best-practices/how-we-style/6-how-we-style-conclusion",
          ],
        },
        {
          type: "category",
          label: "How we build our metrics",
          link: {
            type: "doc",
            id: "best-practices/how-we-build-our-metrics/semantic-layer-1-intro",
          },
          items: [
            "best-practices/how-we-build-our-metrics/semantic-layer-1-intro",
            "best-practices/how-we-build-our-metrics/semantic-layer-2-setup",
            "best-practices/how-we-build-our-metrics/semantic-layer-3-build-semantic-models",
            "best-practices/how-we-build-our-metrics/semantic-layer-4-build-metrics",
            "best-practices/how-we-build-our-metrics/semantic-layer-5-advanced-metrics",
            "best-practices/how-we-build-our-metrics/semantic-layer-6-terminology",
            "best-practices/how-we-build-our-metrics/semantic-layer-7-semantic-structure",
            "best-practices/how-we-build-our-metrics/semantic-layer-8-refactor-a-rollup",
            "best-practices/how-we-build-our-metrics/semantic-layer-9-conclusion",
          ],
        },
        {
          type: "category",
          label: "How to use Wizard in your dbt project",
          link: {
            type: "doc",
            id: "best-practices/how-to-use-wizard/wizard-1-intro",
          },
          items: [
            "best-practices/how-to-use-wizard/wizard-2-understand-project",
            "best-practices/how-to-use-wizard/wizard-3-validate-changes",
            "best-practices/how-to-use-wizard/wizard-4-data-informed-tests",
            "best-practices/how-to-use-wizard/wizard-5-debug-failed-job",
            "best-practices/how-to-use-wizard/wizard-6-production-deferral",
            "best-practices/how-to-use-wizard/wizard-7-semantic-layer",
            "best-practices/how-to-use-wizard/wizard-8-plugins-hooks",
          ],
        },
        {
          type: "category",
          label: "How we build our dbt Mesh projects",
          link: {
            type: "doc",
            id: "best-practices/how-we-mesh/mesh-1-intro",
          },
          items: [
            "best-practices/how-we-mesh/mesh-2-who-is-dbt-mesh-for",
            "best-practices/how-we-mesh/mesh-3-structures",
            "best-practices/how-we-mesh/mesh-4-implementation",
            "best-practices/how-we-mesh/mesh-6-coordinate-versions",
            "best-practices/how-we-mesh/mesh-5-faqs",
          ],
        },
        {
          type: "category",
          label: "How to handle real-time data",
          link: {
            type: "doc",
            id: "best-practices/how-we-handle-real-time-data/1-intro",
          },
          items: [
            "best-practices/how-we-handle-real-time-data/1-intro",
            "best-practices/how-we-handle-real-time-data/2-incremental-patterns",
            "best-practices/how-we-handle-real-time-data/3-warehouse-native-features",
            "best-practices/how-we-handle-real-time-data/4-lambda-views",
            "best-practices/how-we-handle-real-time-data/5-views-only-pattern",
            "best-practices/how-we-handle-real-time-data/6-operational-considerations",
          ],
        },
        {
          type: "category",
          label: "Materialization best practices",
          link: {
            type: "doc",
            id: "best-practices/materializations/materializations-guide-1-guide-overview",
          },
          items: [
            "best-practices/materializations/materializations-guide-2-available-materializations",
            "best-practices/materializations/materializations-guide-3-configuring-materializations",
            "best-practices/materializations/materializations-guide-4-incremental-models",
            "best-practices/materializations/materializations-guide-5-best-practices",
            "best-practices/materializations/materializations-guide-6-examining-builds",
            "best-practices/materializations/materializations-guide-7-conclusion",
          ],
        },
        "best-practices/idempotence",
        "best-practices/dont-nest-your-curlies",
        "best-practices/clone-incremental-models",
        "best-practices/optimize-static-analysis-for-development-and-deployment",
        "best-practices/writing-custom-generic-tests",
        "best-practices/best-practice-workflows",
        "best-practices/dbt-unity-catalog-best-practices",
      ],
    },
  ],
  community: [
    {
      type: "doc",
      id: "community/join",
    },
    {
      type: "category",
      label: "Contributing",
      link: {
        type: "doc",
        id: "community/contribute",
      },
      items: [
        {
          type: "doc",
          label: "Become a contributor",
          id: "community/contribute",
        },
        "community/contributing/contributing-writing",
        "community/contributing/contributing-coding",
        "community/contributing/contributing-online-community",
        "community/contributing/contributing-realtime-events",
      ],
    },
    {
      type: "category",
      label: "Additional resources",
      items: [
        "community/resources/viewpoint",
        "community/resources/code-of-conduct",
        "community/resources/community-rules-of-the-road",
        "community/resources/maintaining-a-channel",
        "community/resources/forum-guidelines",
        "community/resources/getting-help",
        "community/resources/organizing-inclusive-events",
        "community/resources/contributor-expectations",
        "community/resources/oss-sa-projects",
        "community/resources/contributor-license-agreements",
        "community/resources/jobs-terms-and-conditions",
        "community/resources/speaking-at-a-meetup",
      ],
    },
  ],
  SQLReference: [
    {
      type: "category",
      label: "SQL Reference",
      link: {
        type: "generated-index",
        title: "SQL Reference",
        description:
          "The SQL Reference is a collection of SQL functions and keywords that you can use during your daily data work.",
        slug: "/sql-reference",
      },
      items: [
        {
          type: "category",
          label: "Statements",
          items: [
            "sql-reference/statements/select",
            "sql-reference/statements/from",
            "sql-reference/statements/case",
            "sql-reference/statements/group-by",
            "sql-reference/statements/distinct",
          ],
        },
        {
          type: "category",
          label: "Aggregate Functions",
          items: [
            "sql-reference/aggregate-functions/avg",
            "sql-reference/aggregate-functions/count",
            "sql-reference/aggregate-functions/max",
            "sql-reference/aggregate-functions/min",
            "sql-reference/aggregate-functions/round",
            "sql-reference/aggregate-functions/sum",
            "sql-reference/aggregate-functions/array-agg",
          ],
        },
        {
          type: "category",
          label: "Clauses",
          items: [
            "sql-reference/clauses/where",
            "sql-reference/clauses/having",
            "sql-reference/clauses/limit",
            "sql-reference/clauses/order-by",
          ],
        },
        {
          type: "category",
          label: "Date Functions",
          items: [
            "sql-reference/date-functions/dateadd",
            "sql-reference/date-functions/datediff",
            "sql-reference/date-functions/datepart",
            "sql-reference/date-functions/datetrunc",
          ],
        },
        {
          type: "category",
          label: "String Functions",
          items: [
            "sql-reference/string-functions/upper",
            "sql-reference/string-functions/lower",
            "sql-reference/string-functions/concat",
            "sql-reference/string-functions/trim",
          ],
        },
        {
          type: "category",
          label: "Window Functions",
          items: [
            "sql-reference/window-functions/rank",
            "sql-reference/window-functions/row-number",
          ],
        },
        {
          type: "category",
          label: "Operators",
          items: [
            "sql-reference/operators/between",
            "sql-reference/operators/in",
            "sql-reference/operators/or",
            "sql-reference/operators/ilike",
            "sql-reference/operators/like",
            "sql-reference/operators/and",
            "sql-reference/operators/not",
            "sql-reference/operators/any-all",
          ],
        },
        {
          type: "category",
          label: "Joins",
          items: [
            "sql-reference/joins/inner-join",
            "sql-reference/joins/outer-join",
            "sql-reference/joins/self-join",
            "sql-reference/joins/cross-join",
            "sql-reference/joins/left-join",
            "sql-reference/joins/right-join",
          ],
        },
        {
          type: "category",
          label: "Data Types",
          items: [
            "sql-reference/data-type/data-types",
            "sql-reference/data-type/strings",
          ],
        },
        {
          type: "category",
          label: "Other",
          items: ["sql-reference/other/cast", "sql-reference/other/comments"],
        },
      ],
    },
  ],
  faqs: [
    {
      type: "category",
      label: "Frequently asked questions",
      link: {
        type: "generated-index",
        title: "Frequently asked questions",
        description:
          "Our Frequently Asked Questions (FAQs) section is a space where you can find an answer to some questions we get asked a lot (but that we’re happy to answer!). If you have a question or are still stuck on something, just reach out to us by emailing support@getdbt.com or clicking on the chat widget, and we’ll do our best to help out.",
        slug: "/docs/faqs",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "faqs",
        },
      ],
    },
  ],
  support: [
    "docs/dbt-support",
    {
      type: "category",
      label: "Billing",
      collapsed: true,
      items: [
        "docs/platform/billing",
        "docs/platform/billing/plans-and-billing",
        "docs/platform/billing/how-pricing-works",
        "docs/platform/billing/dbt-state-usage",
        "docs/platform/billing/dbt-ai-usage",
        "docs/platform/billing/managing-usage",
        "docs/platform/billing/optimize-costs",
        "docs/platform/billing-faqs",
      ],
    },
    "docs/dbt-licensing",
  ],
};

module.exports = sidebarSettings;
