name: Add needs-review and size/XL pull requests to projects

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/dbt-labs/projects/14
          github-token: ${{ secrets.PROJECT_NEXT }}
          labeled: content, developer blog, guides
          label-operator: OR
