name: cypress tests

on:
  pull_request:
    branches:
      - current

jobs:
  start-workflow:
    name: start workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: npm install
        run: cd website && npm ci

      - name: setup env
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number ${{ github.event_path }})
          echo "PR_NUMBER=${PR_NUMBER}" >> ${GITHUB_ENV}

      - name: run cypress e2e 
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome
          working-directory: website
          spec: cypress/e2e/*.cy.js
          wait-on: https://deploy-preview-${{ env.PR_NUMBER }}--docs-getdbt-com.netlify.app
          wait-on-timeout: 600
        env:
          CYPRESS_BASE_URL: https://deploy-preview-${{ env.PR_NUMBER }}--docs-getdbt-com.netlify.app

      - name: Screenshot artifact upload
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots