name: Run ESLint Checks
on: push

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'

    - name: Install Packages
      run: cd website && npm ci
      
    - name: Run ESLint
      run: cd website && npm run lintAll
