on: [pull_request_target]
name: team-label
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  team-labeler:
    runs-on: ubuntu-latest
    permissions:
       contents: read
       pull-requests: write
    steps:
    - uses: JulienKode/team-labeler-action@v1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
